Training data: 360
Validation data: 240
input_samples (?, 32000)
input_samples_reshape (?, 32000, 1)
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
3D Conv Out: (?, 50, 32, 32, 64)
3D Conv Out Reshape: (?, 32, 32, 64)
Resnet18 Out: (?, 1, 1, 512)
Resnet18 Linear Out: (?, 256)
Input to GRU: (?, 50, 256)
GRU Out: (?, 50, 29)
ResNet LSTM Pretrain weights loaded
outv: (?, 200, 256)
outa: (?, 200, 256)
attn_out: (?, 200, 256)
attn_states: (?, 200, 200)
fusion: (?, 200, 512)
up1: (?, 700, 256)
up2: (?, 2700, 64)
up3: (?, 10700, 16)
up4: (?, 32025, 4)
out_samples: (?, 32000, 1)
output_concats: (?, 32000, 2)

==================================================================================================
Total params: 40,300,399
Trainable params: 40,245,615
Non-trainable params: 54,784
__________________________________________________________________________________________________

Pred: (24, 32000)
GT: (24, 32000)
Pred: (24, 32000)
GT: (24, 32000)
Pred: (24, 32000)
GT: (24, 32000)
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/2
1/5 [=====>........................] - ETA: 8:47 - loss: 53.9498 - snr_acc: -53.94982/5 [===========>..................] - ETA: 3:19 - loss: 51.1158 - snr_acc: -51.11583/5 [=================>............] - ETA: 1:29 - loss: 47.8108 - snr_acc: -47.81074/5 [=======================>......] - ETA: 33s - loss: 47.1046 - snr_acc: -47.1046  1/10 [==>...........................] - ETA: 1:17 - loss: 42.6440 - snr_acc: -42.6440 2/10 [=====>........................] - ETA: 35s - loss: 43.9891 - snr_acc: -43.9891  3/10 [========>.....................] - ETA: 21s - loss: 44.9843 - snr_acc: -44.9843 4/10 [===========>..................] - ETA: 14s - loss: 44.8432 - snr_acc: -44.8432 5/10 [==============>...............] - ETA: 9s - loss: 45.0095 - snr_acc: -45.0095  6/10 [=================>............] - ETA: 6s - loss: 44.5029 - snr_acc: -44.5029 7/10 [====================>.........] - ETA: 4s - loss: 43.8894 - snr_acc: -43.8894 8/10 [=======================>......] - ETA: 2s - loss: 44.2832 - snr_acc: -44.2832 9/10 [==========================>...] - ETA: 1s - loss: 44.1854 - snr_acc: -44.185410/10 [==============================] - 11s 1s/step - loss: 44.0671 - snr_acc: -44.0671
Traceback (most recent call last):
  File "main_tasnet.py", line 167, in <module>
    callbacks=[reducelronplateau, checkpoint_save_weights, LoggingCallback(print_fcn=log_to_file), metrics_crm], verbose = 1)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training.py", line 1426, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.5/dist-packages/wandb/keras/__init__.py", line 104, in new_generator
    return old_generator(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training_generator.py", line 232, in model_iteration
    callbacks.on_epoch_end(epoch, epoch_logs, mode=mode)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/callbacks.py", line 251, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/data/AV-speech-separation1/metrics.py", line 342, in on_epoch_end
    atten_outs = attn_states_out_model.predict_generator(DataGenerator_test_samples(val_folders_samp, self.batch_size), steps = int(np.ceil((len(val_folders_samp))/float(self.batch_size))), verbose=0)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training.py", line 1536, in predict_generator
    verbose=verbose)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training_generator.py", line 191, in model_iteration
    batch_outs = batch_function(*batch_data)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training_generator.py", line 437, in predict_on_batch
    return model.predict_on_batch(x)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training.py", line 1287, in predict_on_batch
    inputs, _, _ = self._standardize_user_data(x)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training.py", line 2382, in _standardize_user_data
    exception_prefix='input')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training_utils.py", line 362, in standardize_input_data
    ' but got array with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have shape (32000,) but got array with shape (51400,)
